// <auto-generated />
using System;
using BookRatingSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookRatingSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookRatingDbContext))]
    [Migration("20260623143054_AddBookRatingStatus")]
    partial class AddBookRatingStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookRatingSystem.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("Category");

                    b.HasIndex("Title");

                    b.ToTable("books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Author = "A. Karimov",
                            Category = "Dasturlash",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Algoritm tushunchasi, saralash va qidiruv usullari haqida oʻquv material.",
                            PublishedYear = 2024,
                            Status = "Verified",
                            Title = "Algoritmlar asoslari",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Author = "D. Rahimov",
                            Category = "Database",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Relatsion maʼlumotlar bazasi, SQL va loyihalash asoslari.",
                            PublishedYear = 2023,
                            Status = "Verified",
                            Title = "Maʼlumotlar bazasi",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Author = "S. Aliyev",
                            Category = "Tarmoq",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kompyuter tarmoqlarining asosiy protokollari va amaliy qoʻllanilishi.",
                            PublishedYear = 2022,
                            Status = "Verified",
                            Title = "Kompyuter tarmoqlari",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("BookRatingSystem.Domain.Entities.BookRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BanReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ban_reason");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("New")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("book_ratings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            BookId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Comment = "Mavzular sodda tushuntirilgan.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 0, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "New",
                            UserId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            BookId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Comment = "Amaliy misollar foydali.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 0, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "New",
                            UserId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            BookId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Comment = "Database loyihalash uchun qulay qoʻllanma.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 0, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "New",
                            UserId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Value = 5
                        });
                });

            modelBuilder.Entity("BookRatingSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user01@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0wMQ==:zSd6h5V1wdpG1ZYdtbgZAeCgizz+WHwKSbeVrQm9PG8=",
                            Username = "user01"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user02@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0wMg==:cfJdJL9XutCfXCnLKAjefa+WYPQb/LqhFdwLWyzE8jQ=",
                            Username = "user02"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user03@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0wMw==:cn9ONRzRx+NmxXa7f7SPv5CXYstD4tMSq/yjrhrCoMQ=",
                            Username = "user03"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user04@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0wNA==:2SYUOW50hDBlp+z8iOG0ttGlr8wlKYgzYS4IuM2ArqQ=",
                            Username = "user04"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user05@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0wNQ==:bzmJJZjJl2bSUBfkvFyHN1bBgPYPORpwKTGag2nFjtY=",
                            Username = "user05"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user06@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0wNg==:cMb0sfq0hH8EYqDP+aqgjt8FiWfDwmdxnF68riL8rBU=",
                            Username = "user06"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user07@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0wNw==:6/v/glazk6XiDjtj2kRLggc/xAGvdmlp3w+AaWuPvlw=",
                            Username = "user07"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user08@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0wOA==:kpZ2X+KmGWrCwHYHrXresTrCUJBj7HGK1jCqdYklogU=",
                            Username = "user08"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user09@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0wOQ==:JB8H1epXgYaa5SmwuES03kPtMvsTJ5Z44UwpVRsbIYE=",
                            Username = "user09"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user10@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0xMA==:AhGFRTegNfBqz+VCkdZqf3d+9fidRfs12zfMVG49Z98=",
                            Username = "user10"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user11@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0xMQ==:61LNsJWaJcT6JwsnpSWLeSIEJFBnhsEwiJOKykOLQw8=",
                            Username = "user11"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user12@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0xMg==:htxKhihDN84cU4qpPhFoY/r6lMU7p/fJbf7XJgQVbmk=",
                            Username = "user12"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user13@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0xMw==:neqv9wU7oH6M3dycNvbKnYrHtESdWmCz7FIgYJD5X+c=",
                            Username = "user13"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user14@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0xNA==:bjF9JAucLgOUEKDpBGfz1NRzAuNj0kmoZ6S4RmoS36o=",
                            Username = "user14"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user15@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0xNQ==:Q93EidFVLYD6Df01FA0drMsWY5+Hfw8H7N+mMQgWi68=",
                            Username = "user15"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user16@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0xNg==:7cKp8HE+8ouf1PveJeUNbKdETAiuVvfO0WGwZBMf2yM=",
                            Username = "user16"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user17@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0xNw==:8chrpinbAXrVWQH3DE5KsrQbieIOo2zM7xgy0EWq86w=",
                            Username = "user17"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user18@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0xOA==:5c46WnwWp+bSSht2oAXwEJo3qoINB96lIY8c6PQaOoU=",
                            Username = "user18"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user19@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0xOQ==:IRAoedGtpr0NBaoobPGy5yMw3XaYaw9EU19TcK7tiZ0=",
                            Username = "user19"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user20@bookrate.uz",
                            IsAdmin = false,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtdXNlci0yMA==:5ktXe+iVYBAd0my8ohEId3hyX1aPh1aYSJirTJutipY=",
                            Username = "user20"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@bookrate.uz",
                            IsAdmin = true,
                            PasswordHash = "pbkdf2-sha256:100000:Ym9va3JhdGUtYWRtaW4tMDE=:eBcb6RyQ/zvA5gcKCLEytg/IOkowlvvXNQ8S5rqs4HQ=",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BookRatingSystem.Domain.Entities.BookRating", b =>
                {
                    b.HasOne("BookRatingSystem.Domain.Entities.Book", "Book")
                        .WithMany("Ratings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookRatingSystem.Domain.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookRatingSystem.Domain.Entities.Book", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("BookRatingSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
